In [2]:
x = [[1,2,-33],[-4,5,6]]

In [3]:
import numpy as np 

In [7]:
x = np.array(x)

In [9]:
2./x

array([[ 2.        ,  1.        , -0.06060606],
       [-0.5       ,  0.4       ,  0.33333333]])

In [56]:
y = np.maximum(0,x)

In [57]:
j = np.array(x, copy=False)

In [59]:
y

array([[1, 2, 0],
       [0, 5, 6]])

In [45]:
x[0][0] = 300

In [70]:
z = np.sum(y, axis =1,keepdims= True)

In [71]:
y + z

array([[ 4,  5,  3],
       [11, 16, 17]])

In [1]:
z

NameError: name 'z' is not defined

In [74]:
a = np.ones((2,3))

In [75]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
x = np.array([[2,2],[2,2],[2,2]])

In [77]:
a*x

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [95]:
np.ones((2,3))*np.array([[2,2]])

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [88]:
(a - 1./2*np.sum(a, axis=1, keepdims=True)) * (1./(1./2 * np.sum((a - 1./2*np.sum(a, axis=1, keepdims=True))**2, axis = 1, keepdims = True)+1))

array([[-0.36363636, -0.36363636, -0.36363636],
       [-0.36363636, -0.36363636, -0.36363636]])